env:
  - TREETAGGER_HOME=/home/$USER/tree-tagger/cmd/
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - sudo apt-get remove automake
install:
  - ./install_treetagger.sh
  - sudo -H ./install_dependencies.sh
  - sudo chmod 777 -R crfpp
  - cd crfpp/
  - export C_INCLUDE_PATH=/usr/local/include/:${C_INCLUDE_PATH}
  - export CPLUS_INCLUDE_PATH=/usr/local/include/:${CPLUS_INCLUDE_PATH}
  - pip install -e python
  - cd
  - git clone https://github.com/mromanello/hucit_kb.git
  - cd hucit_kb
  - pip install -r requirements.txt
  - pip install .
  - sudo -H ./install_3stores.sh
  - pip install http://www.antlr3.org/download/Python/antlr_python_runtime-3.1.3.tar.gz https://github.com/mromanello/pyCTS/archive/master.zip  citation_parser
  - cd $TRAVIS_BUILD_DIR
  - pip install -e lib/
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install .
# command to run tests
script: pytest -s -vv --cov=citation_extractor tests/test_ned.py::test_instantiate_ml_citation_matcher
#script: pytest -s -vv --cov=citation_extractor --ignore=tests/test_eval.py
#script: travis_wait 60 pytest -s -vv --cov=citation_extractor
after_success:
  - codecov
