env:
  - TREETAGGER_HOME=/home/$USER/tree-tagger/cmd/
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - sudo apt-get remove automake
install:
  - ./install_treetagger.sh
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install .
# command to run tests
script: pytest -vv --cov=citation_extractor --ignore=tests/test_eval.py tests/test_citation_extractor.py tests/test_eval.py::test_eval_ner
#script: travis_wait 60 pytest -s -vv --cov=citation_extractor
after_success:
  - codecov
