language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
install:
  - sudo ./install_dependencies.sh
  - "pip install -e crfpp/python"
  - "pip install -e lib/"
  - "pip install -U -r requirements.txt"
# command to run tests
script: pytest
