language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update --fix-missing
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - sudo apt-get remove automake
install:
  - sudo -H ./install_dependencies.sh
  - sudo chmod 777 -R crfpp
  - cd crfpp/
  - export C_INCLUDE_PATH=/usr/local/include/:${C_INCLUDE_PATH}
  - export CPLUS_INCLUDE_PATH=/usr/local/include/:${CPLUS_INCLUDE_PATH}
  - pip install -e python
  - cd
  - git clone https://github.com/mromanello/hucit_kb.git
  - cd hucit_kb
  - pip install -r requirements.txt
  - pip install .
  - git clone https://github.com/mromanello/CitationParser.git
  - cd CitationParser/
  - pip install wheel
  - pip wheel --wheel-dir ../ -r requirements.txt
  - pip install -r requirements.txt
  - pip install .
  - cd $TRAVIS_BUILD_DIR
  - pip install -e lib/
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest -vv
